# Generated by Django 6.0.5 on 2026-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('aciklama', models.CharField(max_length=200)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori', models.CharField(max_length=100)),
            ],
        ),
    ]
